### ISSUE TITLE
setcoef bug

### ISSUE THREAD

**Issue by Xeenych** [AER-RC/RRTMG_LW#11]
setcoef function makes
rat_h2och4 and other rat_xxx arrays.

rat_h2oo3
rat_h2oo3_1
rat_h2on2o
rat_h2on2o_1

arrays and possibly others are filled with NaNs by half after call to setcoef subroutine.
Futher in the code there are no checks for NaN in rat_xxxx arrays.

rat_xxx should be set to some adequate value at initialisation or in the code

**Comment by mjiacono** [comment]
When RRTMG is compiled as a stand-alone one-column model, most of the arrays with a vertical dimension are declared with the constant parameter mxlay=603. When executing, the model only accesses arrays with this dimension over the range of the number of vertical layers requested to perform the calculation. As a result, this condition does not affect the functionality of the column model. When RRTMG is compiled as a subroutine as part of a host model, the arrays with a layer dimension are declared using the number of vertical layers provided by the host model, and so the reported condition will not occur. No code changes are necessary.
