### ISSUE TITLE
possible typos in rrtmg_lw_read_nc.f90

### ISSUE THREAD

**Issue by drbel8** [AER-RC/RRTMG_LW#13]
I think there are two typos in rrtmg_lw_read_nc.f90, possibly coming from a replace in the file 
 
../src/rrtmg_lw_read_nc.f90(762): error #6404: This name does not have a type, and must have an explicit type.   [IM2]
	status(1_im2)  = nf90_inq_varid(ncid,"H20ForeignAbsorptionCoefficients",varID)
-----------------^
../src/rrtmg_lw_read_nc.f90(762): error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [IM2]
	status(1_im2)  = nf90_inq_varid(ncid,"H20ForeignAbsorptionCoefficients",varID)
-----------------^
../src/rrtmg_lw_read_nc.f90(763): error #6404: This name does not have a type, and must have an explicit type.   [IM3]
	status(1_im3)  = nf90_get_var(ncid, varID, forrefo, &
-----------------^
../src/rrtmg_lw_read_nc.f90(763): error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [IM3]
	status(1_im3)  = nf90_get_var(ncid, varID, forrefo, &

I suppose they should be
status(12) and status(13)

**Comment by mjiacono** [comment]
We are already aware of these typos in this module, and the fixes will be in the next release. You are correct that "status(1_im2)" should be "status(12)" and "status(1_im3)" should be "status(13)". Thank you for reporting.
