### ISSUE TITLE
possible memory access to outside of array

### ISSUE THREAD

**Issue by Xeenych** [AER-RC/RRTMG_LW#6]
Here:
https://github.com/AER-RC/RRTMG_LW/blob/6e8786ab7b1a3bd3c44fad5bca01335f04c44207/src/rrtmg_lw_rtrnmr.f90#L497
```
            if (istcldd(lev).ne.1) then
	        faccmb1d(lev-1) = max(0.,min(cldfrac(lev+1)-cldfrac(lev), &
        	    cldfrac(lev-1)-cldfrac(lev)))
            	faccmb2d(lev-1) = max(0.,min(cldfrac(lev)-cldfrac(lev+1), &
                    cldfrac(lev)-cldfrac(lev-1)))
	    endif
```
the outer cycle is `do lev = nlayers, 1, -1`
cldfrac is dimension(:)
when lev =1 , then cldfrac(lev-1) is accessing out of bounds

This occurs when cldfrac(1) is larger than 1.e-6_rb;

**Comment by Xeenych** [comment]
Possible soultions are to emit runtime error or to make cldfrac(0:nlayers+1)
I have an older version of RRTMG_LW, where cldfrac (0:nlayers+1)

**Comment by mjiacono** [comment]
Since the variables faccmb1d and faccmb2d are set previously to zero in the condition when lev = 1 and icldlyr(lev) = 1, then the optimal solution is to prevent the code block from being used when lev = 1, since it isn't needed:

            if (lev.ne.1 .and. istcldd(lev).ne.1) then
                faccmb1d(lev-1) = max(0.,min(cldfrac(lev+1)-cldfrac(lev), &
                    cldfrac(lev-1)-cldfrac(lev)))
                faccmb2d(lev-1) = max(0.,min(cldfrac(lev)-cldfrac(lev+1), &
                    cldfrac(lev)-cldfrac(lev-1)))
            endif

We will implement this change in a future release of the code.
