### ISSUE TITLE
possible incorrect variable used

### ISSUE THREAD

**Issue by Xeenych** [AER-RC/RRTMG_LW#7]
Here
https://github.com/AER-RC/RRTMG_LW/blob/6e8786ab7b1a3bd3c44fad5bca01335f04c44207/src/mcica_subcol_gen_lw.f90#L639

and in some places above the `nlayers` is used instead of `nlay`, but there is no such identifier `nlayers` defined

**Comment by mjiacono** [comment]
This is a known issue, and it will be corrected in the next release of the model.
