### ISSUE TITLE
possible incorrect assignment

### ISSUE THREAD

**Issue by Xeenych** [AER-RC/RRTMG_LW#8]
Here
https://github.com/AER-RC/RRTMG_LW/blob/6e8786ab7b1a3bd3c44fad5bca01335f04c44207/src/mcica_subcol_gen_lw.f90#L619
`CDF(isubcol, i, ilev) = rand_num`
element is assigned to a column

where
`real(kind=rb), dimension(nsubcol, ncol, nlay) :: CDF`
`real(kind=rb), dimension(ncol) :: rand_num`

**Comment by mjiacono** [comment]
This is a known issue, and it will be corrected in the next release of the model.
